PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE transactions(
ID INT PRIMARY KEY,
name TEXT NOT NULL,
value REAL NOT NULL,
date INT NOT NULL
);
CREATE TABLE groups(
ID INT PRIMARY KEY,
name TEXT NOT NULL UNIQUE,
color TEXT NOT NULL
);
CREATE TABLE filters(
ID INT PRIMARY KEY,
groupID INT NOT NULL,
value TEXT NOT NULL,
FOREIGN KEY (groupID) REFERENCES groups(id)
);
CREATE TABLE transactionGroups(
ID INT PRIMARY KEY,
transactionID INT NOT NULL,
groupID INT NOT NULL,
FOREIGN KEY (transactionID) REFERENCES transactions(ID),
FOREIGN KEY (groupID) REFERENCES groups(ID)
);
COMMIT;
