PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS transactions(
ID INTEGER PRIMARY KEY,
name TEXT NOT NULL,
value REAL NOT NULL,
date INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS groups(
ID INTEGER PRIMARY KEY,
name TEXT NOT NULL UNIQUE,
color TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS filters(
ID INTEGER PRIMARY KEY,
groupID INTEGER NOT NULL,
keyword TEXT NOT NULL,
FOREIGN KEY (groupID) REFERENCES groups(id)
);
CREATE TABLE IF NOT EXISTS transactionGroups(
ID INTEGER PRIMARY KEY,
transactionID INTEGER NOT NULL,
groupID INTEGER NOT NULL,
FOREIGN KEY (transactionID) REFERENCES transactions(ID),
FOREIGN KEY (groupID) REFERENCES groups(ID)
);
COMMIT;